"""
export_swatplus.py
==================
Generates all SWAT+ climate input files from the NOAA daily CSVs:

    Per station:
        <station_name>.pcp   — daily precipitation
        <station_name>.tmp   — daily TMAX / TMIN

    Index files:
        pcp.cli              — lists all .pcp filenames
        tmp.cli              — lists all .tmp filenames
        weather-sta.cli      — one row per station (lat, lon, elev, pcp, tmp)

    GIS:
        stations.shp/.shx/.dbf/.prj  — point shapefile of selected stations

Usage from Python:
    from noaa_selector.scripts.export_swatplus import export_swatplus
    export_swatplus(stations_gdf, noaa_folder, output_folder, start_date, end_date)
"""

import os
import zipfile
import datetime
import tempfile

import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point


# ── Helpers ───────────────────────────────────────────────────────────────────

def _safe_name(station_id: str) -> str:
    """Convert a NOAA station ID to a safe filename stem (no colons or spaces)."""
    return station_id.replace(":", "_").replace(" ", "_")


def _to_julian(date: pd.Timestamp) -> int:
    """Return the Julian day-of-year (1-based) for a date."""
    return date.timetuple().tm_yday


def _fill_missing(value, fill=-99.0):
    """Return fill value if NaN, else round to 3 decimals."""
    if pd.isna(value):
        return fill
    return round(float(value), 3)


# ── Per-station file writers ───────────────────────────────────────────────────

def _write_pcp(df: pd.DataFrame, station_id: str, lat: float, lon: float,
               elev: float, out_dir: str, start_date, end_date) -> str:
    """
    Write a SWAT+ .pcp file for one station.
    Returns the filename stem used.
    """
    stem     = _safe_name(station_id)
    filename = stem + ".pcp"
    filepath = os.path.join(out_dir, filename)

    df = df.copy()
    df["DATE"] = pd.to_datetime(df["DATE"])

    # Filter to requested date range and build a complete daily index
    start = pd.Timestamp(start_date)
    end   = pd.Timestamp(end_date)
    full_index = pd.date_range(start, end, freq="D")
    df = df.set_index("DATE").reindex(full_index)

    nbyr  = end.year - start.year + 1
    tstep = 0  # daily
    elev_val = round(elev, 3) if not np.isnan(elev) else 0.0

    lines = []
    lines.append(f"{stem}: Precipitation data - generated by NOAA Station Selector for SWAT+")
    lines.append("nbyr  tstep     lat      lon      elev")
    lines.append(f"{nbyr:4d}  {tstep:5d}  {lat:7.4f}  {lon:8.4f}  {elev_val:8.3f}")

    for date, row in df.iterrows():
        year = date.year
        jday = _to_julian(date)
        prcp = _fill_missing(row.get("PRCP", np.nan))
        lines.append(f"{year}  {jday:3d}  {prcp:.3f}")

    with open(filepath, "w") as f:
        f.write("\n".join(lines) + "\n")

    return filename


def _write_tmp(df: pd.DataFrame, station_id: str, lat: float, lon: float,
               elev: float, out_dir: str, start_date, end_date) -> str:
    """
    Write a SWAT+ .tmp file for one station.
    Returns the filename stem used.
    """
    stem     = _safe_name(station_id)
    filename = stem + ".tmp"
    filepath = os.path.join(out_dir, filename)

    df = df.copy()
    df["DATE"] = pd.to_datetime(df["DATE"])

    start = pd.Timestamp(start_date)
    end   = pd.Timestamp(end_date)
    full_index = pd.date_range(start, end, freq="D")
    df = df.set_index("DATE").reindex(full_index)

    nbyr     = end.year - start.year + 1
    tstep    = 0
    elev_val = round(elev, 3) if not np.isnan(elev) else 0.0

    lines = []
    lines.append(f"{stem}: Temperature data - generated by NOAA Station Selector for SWAT+")
    lines.append("nbyr  tstep     lat      lon      elev")
    lines.append(f"{nbyr:4d}  {tstep:5d}  {lat:7.4f}  {lon:8.4f}  {elev_val:8.3f}")

    for date, row in df.iterrows():
        year = date.year
        jday = _to_julian(date)
        tmax = _fill_missing(row.get("TMAX", np.nan))
        tmin = _fill_missing(row.get("TMIN", np.nan))
        lines.append(f"{year}  {jday:3d}  {tmax:.3f}  {tmin:.3f}")

    with open(filepath, "w") as f:
        f.write("\n".join(lines) + "\n")

    return filename


# ── Index file writers ────────────────────────────────────────────────────────

def _write_pcp_cli(pcp_files: list, out_dir: str):
    lines = ["pcp.cli: list of precipitation files - NOAA Station Selector for SWAT+",
             "filename"]
    lines += pcp_files
    with open(os.path.join(out_dir, "pcp.cli"), "w") as f:
        f.write("\n".join(lines) + "\n")


def _write_tmp_cli(tmp_files: list, out_dir: str):
    lines = ["tmp.cli: list of temperature files - NOAA Station Selector for SWAT+",
             "filename"]
    lines += tmp_files
    with open(os.path.join(out_dir, "tmp.cli"), "w") as f:
        f.write("\n".join(lines) + "\n")


def _write_weather_sta_cli(stations_gdf: gpd.GeoDataFrame,
                            pcp_stems: list, tmp_stems: list,
                            out_dir: str):
    """
    weather-sta.cli — one row per station.
    Columns: name  lat  lon  elev  pcp_file  tmp_file  (slr/hmd/wnd set to 'sim')
    """
    lines = [
        "weather-sta.cli: weather station list - NOAA Station Selector for SWAT+",
        "name          lat        lon        elev    pcp            tmp            "
        "slr   hmd   wnd"
    ]

    for i, (_, row) in enumerate(stations_gdf.iterrows()):
        name    = _safe_name(row.get("id", f"sta_{i}"))[:16].ljust(16)
        lat     = row.geometry.y
        lon     = row.geometry.x
        elev    = row.get("elevation", 0)
        elev    = 0.0 if pd.isna(elev) else float(elev)
        pcp_f   = (pcp_stems[i] if i < len(pcp_stems) else "sim").ljust(16)
        tmp_f   = (tmp_stems[i] if i < len(tmp_stems) else "sim").ljust(16)
        lines.append(
            f"{name}  {lat:9.4f}  {lon:10.4f}  {elev:7.1f}  "
            f"{pcp_f}  {tmp_f}  sim   sim   sim"
        )

    with open(os.path.join(out_dir, "weather-sta.cli"), "w") as f:
        f.write("\n".join(lines) + "\n")


# ── Shapefile writer ──────────────────────────────────────────────────────────

def _write_shapefile(stations_gdf: gpd.GeoDataFrame, out_dir: str):
    """
    Export a point shapefile of the selected stations with key attributes.
    """
    keep_cols = [c for c in ["id", "name", "elevation", "elev_band",
                              "cover_frac", "score", "mindate", "maxdate",
                              "geometry"]
                 if c in stations_gdf.columns]
    shp = stations_gdf[keep_cols].copy()

    # Convert datetime columns to string (shapefiles don't store datetimes well)
    for col in ["mindate", "maxdate"]:
        if col in shp.columns:
            shp[col] = shp[col].astype(str)

    shp_path = os.path.join(out_dir, "stations.shp")
    shp.to_file(shp_path, driver="ESRI Shapefile")
    return shp_path


# ── Main export function ──────────────────────────────────────────────────────

def export_swatplus(
    stations_gdf: gpd.GeoDataFrame,
    noaa_folder: str,
    output_folder: str,
    start_date,
    end_date,
) -> dict:
    """
    Generate all SWAT+ climate input files for the selected stations.

    Parameters
    ----------
    stations_gdf   : GeoDataFrame of selected stations (from select_stations)
    noaa_folder    : path to folder containing downloaded NOAA daily CSVs
    output_folder  : path where SWAT+ files will be written
    start_date     : start of the export period (date / str / Timestamp)
    end_date       : end of the export period

    Returns
    -------
    dict with keys:
        n_pcp       : number of .pcp files written
        n_tmp       : number of .tmp files written
        skipped     : list of station IDs with no local CSV
        output_dir  : path to output folder
        zip_path    : path to zip archive of all output files
    """
    os.makedirs(output_folder, exist_ok=True)

    pcp_files  = []   # filenames  e.g. "GHCND_USC00123456.pcp"
    tmp_files  = []
    pcp_stems  = []   # stems without ext, for weather-sta.cli
    tmp_stems  = []
    skipped    = []

    for _, row in stations_gdf.iterrows():
        sid  = row.get("id", "")
        lat  = row.geometry.y
        lon  = row.geometry.x
        elev = float(row["elevation"]) if "elevation" in row.index and not pd.isna(row["elevation"]) else 0.0

        # Locate local CSV
        csv_fname = sid.replace(":", "_") + ".csv"
        csv_path  = os.path.join(noaa_folder, csv_fname)

        if not os.path.exists(csv_path):
            skipped.append(sid)
            continue

        df = pd.read_csv(csv_path)
        df["DATE"] = pd.to_datetime(df["DATE"])

        # .pcp
        pcp_fn = _write_pcp(df, sid, lat, lon, elev, output_folder, start_date, end_date)
        pcp_files.append(pcp_fn)
        pcp_stems.append(pcp_fn)

        # .tmp
        tmp_fn = _write_tmp(df, sid, lat, lon, elev, output_folder, start_date, end_date)
        tmp_files.append(tmp_fn)
        tmp_stems.append(tmp_fn)

    # Index files
    _write_pcp_cli(pcp_files, output_folder)
    _write_tmp_cli(tmp_files, output_folder)
    _write_weather_sta_cli(
        stations_gdf[~stations_gdf["id"].isin(skipped)].reset_index(drop=True),
        pcp_stems, tmp_stems, output_folder
    )

    # Shapefile
    _write_shapefile(stations_gdf, output_folder)

    # Zip everything for one-click download
    zip_path = output_folder.rstrip("/\\") + "_swatplus.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for fname in os.listdir(output_folder):
            zf.write(os.path.join(output_folder, fname), arcname=fname)

    return {
        "n_pcp":      len(pcp_files),
        "n_tmp":      len(tmp_files),
        "skipped":    skipped,
        "output_dir": output_folder,
        "zip_path":   zip_path,
    }
